# Generated by Django 5.1.1 on 2024-11-20 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def migrate_data(apps,schema_editor):
    LikeComment = apps.get_model('userauth','LikeComment')
    Comment = apps.get_model('userauth', 'Comment')
    User = apps.get_model('auth', 'User')

    for lc in LikeComment.objects.all():
        try:
            cmt = Comment.objects.get(id=lc.old_comment_id)
            user = User.objects.get(username=lc.old_username)
            lc.comment = cmt
            lc.user = user
            lc.save()
        except (Comment.DoesNotExist, User.DoesNotExist):
            continue

class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_alter_comment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='likecomment',
            old_name='comment_id',
            new_name='old_comment_id',
        ),
        migrations.RenameField(
            model_name='likecomment',
            old_name='username',
            new_name='old_username',
        ),
        migrations.AddField(
            model_name='likecomment',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userauth.comment'),
        ),
        migrations.AddField(
            model_name='likecomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.RunPython(migrate_data),
        migrations.RemoveField(
            model_name='likecomment',
            name='old_comment_id',
        ),
        migrations.RemoveField(
            model_name='likecomment',
            name='old_username',
        ),
        
    ]
