# Generated by Django 5.1.1 on 2024-11-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_remove_likecomment_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
