# Generated by Django 5.0 on 2024-10-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('History', 'History'), ('English', 'English')], default='Math', max_length=100),
        ),
    ]
